version: '3.8'

services:
  backend:
    build: ./backend
    container_name: mc-manager-api
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Wajib untuk kontrol Docker
      - ./data:/app/data # PERSISTENCE: Data config dan world disimpan di sini
      - ./backend/uploads:/app/uploads # Temp uploads
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: mc-manager-ui
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  default:
    name: mc-network